version: '3.8'

services:
  anota-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: anota-frontend
    restart: unless-stopped
    ports:
      - "3030:3030"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
      - AUTH_ORIGIN=${AUTH_ORIGIN:-http://localhost:3030}
      - AUTH_SECRET=${AUTH_SECRET:-your-secret-key-here}
      - NUXT_PUBLIC_API_BASE_URL=${NUXT_PUBLIC_API_BASE_URL:-/api/proxy}
      - NUXT_BACKEND_URL=${NUXT_BACKEND_URL:-http://localhost:8000/api/v1}
    env_file:
      - .env
    networks:
      - anota-network
    volumes:
      - ./logs:/app/logs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.anota-frontend.rule=Host(`localhost`)"
      - "traefik.http.services.anota-frontend.loadbalancer.server.port=3000"

networks:
  anota-network:
    driver: bridge

volumes:
  logs:
    driver: local
